spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-demo.ctvs1jqaqfr8.ap-northeast-2.rds.amazonaws.com:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Jkw123789!

  jpa:
   hibernate:
     ddl-auto: update
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true